require 'rails_helper'

describe Tag do
  
  describe 'ifrs lookups and Mappings' do

    it 'should load master IFRS csv' do
      expect(CSV).to receive(:open)
      Tag.load_master_ifrs_csv
    end
     it 'should load master GAAP csv' do
      expect(CSV).to receive(:open)
      Tag.load_master_gaap_csv
    end
    it 'can find unique keys' do
      keys = Tag.extract_unique_keys { [key: "33", key_2: "Hello", "stringKey" => 1234]}
      expect(keys).to eq [:key, :key_2, "stringKey"]
    end
    it 'should return IFRS fin stat keys for dash Show lead display' do
      tags = Tag.ifrs_fin_stat_tags
      expect(tags).to eq( {:gp_rev=>["Revenue", "Other trading income"], :gp_cos=>["Cost of sales", "Other direct costs", "Changes in inventories of finished goods and work in progress", "Raw materials and consumables used"], :op_rev=>["Other operating income", "Finance income", "Share of post-tax profits of equity associates", "Share of post-tax profits of equity joint ventures"], :op_cos=>["Administrative expenses", "Distribution expenses", "Other expenses", "Finance expense", "Employee benefit expenses", "Depreciation and amortisation expense", "Research and development", "Other expenses", "Exchange gains arising on translation of foreign operations"], :tax=>["Tax expense"], :pat_cos=>["Loss on property revaluation", "Remeasurements of defined benefit pension schemes", "Share of associates' other"], :ca=>["Inventories", "Trade and other receivables", "Available-for-sale investments", "Derivative financial assets", "Current tax assets", "Other assets", "Cash and cash equivalents", "Assets in disposal groups classified as held for sale", "Finance lease receiveable", "Other receivables", "Deferred tax assets"], :nca=>["Property plant and equipment", "Investment property", "Goodwill", "Other intangible assets", "Finance lease receiveable", "Other financial assets", "Other assets", "Investments in equity-accounted associates", "Investments in equity-accounted joint ventures", "Available-for-sale investments", "Derivative financial assets"], :cl=>["Trade and other payables", "Loans and borrowings", "Derivative financial liabilities", "Income Tax Payable", "Employee benefit liabilities", "Provisions", "Liabilities directly associated with assets in HFS"], :ncl=>["Loans and borrowings", "Derivative financial liabilities", "Employee benefit liabilities", "Provisions ", "Deferred tax liability", "Other financial liabilities", "Deferred revenue", "Other liabilities"], :eq=>["Revaluation reserve", "Available-for-sale reserve", "Cash flow hedging reserve", "Foreign exchange reserve", "Issued capital and share premium", "Other reserves", "Retained earnings", "Equity attributable to parent", "Non-controlling interest", "Share capital", "Share premium reserve", "Shares to be issued", "No-Mapping"]})
      expect(tags.keys.count).to eq 11
    end
    it 'should return GAAP fin stat keys for dash Show lead display' do
      tags = Tag.gaap_fin_stat_tags
      expect(tags).to eq( {:gp_sales=>["Sales", "Other sales"], :gp_cos=>["Purchases", "Decrease in stocks", "Subcontractor costs", "Direct labour", "Carriage", "Discounts allowed", "Commissions payable", "Other direct costs"], :op_sales=>["Other operating income"], :op_dis=>["Distribution costs"], :op_admin=>["Wages and salaries", "Directors' salaries", "Pensions", "Bonuses", "Employer's NI", "Temporary staff and recruitment", "Staff training and welfare", "Travel and subsistence", "Motor expenses", "Entertaining", "Telephone and fax", "Postage", "Stationery and printing", "Courier services", "Information and publications", "Subscriptions", "Bank charges", "Insurance", "Equipment expensed", "Equipment hire", "Software", "Repairs and maintenance", "Depreciation", "Amortisation of goodwill", "Bad debts", "Sundry expenses", "Audit fees", "Accountancy fees", "Solicitors fees", "Consultancy fees", "Management fees", "Advertising and PR", "Other legal and professional", "Rent", "Rates", "Service charges", "Light and heat", "Cleaning", "Use of home", "Depreciation of owned fixed assets", "Depreciation of leased assets", "Amortisation of goodwill", "Directors' remuneration", "Pension costs", "Auditors' remuneration", "Exceptional costs", "Non-equity dividends"], :pbiat_sales=>["Interest receiveable", "Other interest receceiveable", "Other finance income"], :pbiat_cos=>["Interest payable", "Other interest payable", "Other finance costs"], :tax_cos=>["Taxation on profit"], :pat_cos=>["Equity dividends", "Non-equity dividends"]})
      expect(tags.keys.count).to eq 9
    end
    it 'should return IFRS user Select options' do
      tags = Tag.ifrs_user_select_options
      expect(tags).to eq( ["Revenue", "Other trading income", "Cost of sales", "Other direct costs", "Other operating income", "Finance income", "Share of post-tax profits of equity associates", "Share of post-tax profits of equity joint ventures", "Administrative expenses", "Distribution expenses", "Other expenses", "Finance expense", "Tax expense", "Changes in inventories of finished goods and work in progress", "Raw materials and consumables used", "Employee benefit expenses", "Depreciation and amortisation expense", "Research and development", "Other expenses", "Loss on property revaluation", "Remeasurements of defined benefit pension schemes", "Share of associates' other", "Exchange gains arising on translation of foreign operations", "Inventories", "Trade and other receivables", "Available-for-sale investments", "Derivative financial assets", "Current tax assets", "Other assets", "Cash and cash equivalents", "Assets in disposal groups classified as held for sale", "Finance lease receiveable", "Property plant and equipment", "Investment property", "Goodwill", "Other intangible assets", "Finance lease receiveable", "Other financial assets", "Other assets", "Investments in equity-accounted associates", "Investments in equity-accounted joint ventures", "Available-for-sale investments", "Derivative financial assets", "Other receivables", "Deferred tax assets", "Trade and other payables", "Loans and borrowings", "Derivative financial liabilities", "Income Tax Payable", "Employee benefit liabilities", "Provisions", "Liabilities directly associated with assets in HFS", "Loans and borrowings", "Derivative financial liabilities", "Employee benefit liabilities", "Provisions ", "Deferred tax liability", "Other financial liabilities", "Deferred revenue", "Other liabilities", "Revaluation reserve", "Available-for-sale reserve", "Cash flow hedging reserve", "Foreign exchange reserve", "Issued capital and share premium", "Other reserves", "Retained earnings", "Equity attributable to parent", "Non-controlling interest", "Share capital", "Share premium reserve", "Shares to be issued", "No-Mapping"])
      expect(tags.count).to eq 73
    end
    it 'should return GAAP select options' do
      tags = Tag.gaap_user_options
      expect(tags).to eq( ["Sales", "Other sales", "Purchases", "Decrease in stocks", "Subcontractor costs", "Direct labour", "Carriage", "Discounts allowed", "Commissions payable", "Other direct costs", "Other operating income", "Distribution costs", "Wages and salaries", "Directors' salaries", "Pensions", "Bonuses", "Employer's NI", "Temporary staff and recruitment", "Staff training and welfare", "Travel and subsistence", "Motor expenses", "Entertaining", "Rent", "Rates", "Service charges", "Light and heat", "Cleaning", "Use of home", "IT costs", "Digital and internet", "Telephone and fax", "Postage", "Stationery and printing", "Courier services", "Information and publications", "Subscriptions", "Bank charges", "Insurance", "Equipment expensed", "Equipment hire", "Software", "Repairs and maintenance", "Depreciation", "Amortisation of goodwill", "Bad debts", "Sundry expenses", "Audit fees", "Accountancy fees", "Solicitors fees", "Consultancy fees", "Management fees", "Advertising and PR", "Other legal and professional", "Depreciation of owned fixed assets", "Depreciation of leased assets", "Amortisation of goodwill", "Directors' remuneration", "Pension costs", "Auditors' remuneration", "Exceptional costs", "Non-equity dividends", "Interest receiveable", "Other interest receceiveable", "Bank loan interest payable", "Operating lease charges", "Hire purchase charges", "Finance lease charges", "Other finance income", "Other interest payable", "Other finance costs", "Taxation on profit", "Equity dividends", "Non-equity dividends", "Trade debtors", "Trade creditors", "Corporation tax", "Other taxes and social security costs", "Bank loans", "Obligations under lease contracts", "Plant & machinery cost - additions", "Plant & machinery cost - disposals", "Motor vehicles cost - additions", "Motor vehicles cost - disposals", "Land & buildings cost - additions", "Land & buildings cost - disposals", "Intangible assets cost - additions", "Intangible assets cost - disposals", "Other investments cost - additions", "Other investments cost - disposals", "No-Mapping"])
      expect(tags.count).to eq 90
    end
    it 'can load mappings UKGAAP' do
      tags = Tag.load_monea_tag_mappings("UKGAAP")
      expect(tags).to eq( {"Sales"=>"gp_sales", "Other sales"=>"gp_sales", "Purchases"=>"gp_cos", "Decrease in stocks"=>"gp_cos", "Subcontractor costs"=>"gp_cos", "Direct labour"=>"gp_cos", "Carriage"=>"gp_cos", "Discounts allowed"=>"gp_cos", "Commissions payable"=>"gp_cos", "Other direct costs"=>"gp_cos", "Other operating income"=>"op_sales", "Distribution costs"=>"op_dis", "Wages and salaries"=>"op_admin", "Directors' salaries"=>"op_admin", "Pensions"=>"op_admin", "Bonuses"=>"op_admin", "Employer's NI"=>"op_admin", "Temporary staff and recruitment"=>"op_admin", "Staff training and welfare"=>"op_admin", "Travel and subsistence"=>"op_admin", "Motor expenses"=>"op_admin", "Entertaining"=>"op_admin", "Telephone and fax"=>"op_admin", "Postage"=>"op_admin", "Stationery and printing"=>"op_admin", "Courier services"=>"op_admin", "Information and publications"=>"op_admin", "Subscriptions"=>"op_admin", "Bank charges"=>"op_admin", "Insurance"=>"op_admin", "Equipment expensed"=>"op_admin", "Equipment hire"=>"op_admin", "Software"=>"op_admin", "Repairs and maintenance"=>"op_admin", "Depreciation"=>"op_admin", "Amortisation of goodwill"=>"op_admin", "Bad debts"=>"op_admin", "Sundry expenses"=>"op_admin", "Audit fees"=>"op_admin", "Accountancy fees"=>"op_admin", "Solicitors fees"=>"op_admin", "Consultancy fees"=>"op_admin", "Management fees"=>"op_admin", "Advertising and PR"=>"op_admin", "Other legal and professional"=>"op_admin", "Rent"=>"op_admin", "Rates"=>"op_admin", "Service charges"=>"op_admin", "Light and heat"=>"op_admin", "Cleaning"=>"op_admin", "Use of home"=>"op_admin", "Depreciation of owned fixed assets"=>"op_admin", "Depreciation of leased assets"=>"op_admin", "Directors' remuneration"=>"op_admin", "Pension costs"=>"op_admin", "Auditors' remuneration"=>"op_admin", "Exceptional costs"=>"op_admin", "Non-equity dividends"=>"pat_cos", "Interest receiveable"=>"pbiat_sales", "Other interest receceiveable"=>"pbiat_sales", "Interest payable"=>"pbiat_cos", "Other interest payable"=>"pbiat_cos", "Other finance income"=>"pbiat_sales", "Other finance costs"=>"pbiat_cos", "Taxation on profit"=>"tax_cos", "Equity dividends"=>"pat_cos"} )
      expect(tags.count).to eq 66
    end
    it 'can load mappings IFRS' do
      tags = Tag.load_monea_tag_mappings("IFRS")
      expect(tags).to eq( {"Revenue"=>"GP_Rev", "Other trading income"=>"GP_Rev", "Cost of sales"=>"GP_Cos", "Other direct costs"=>"GP_Cos", "Other operating income"=>"OP_Rev", "Finance income"=>"OP_Rev", "Share of post-tax profits of equity associates"=>"OP_Rev", "Share of post-tax profits of equity joint ventures"=>"OP_Rev", "Administrative expenses"=>"OP_Cos", "Distribution expenses"=>"OP_Cos", "Other expenses"=>"OP_Cos", "Finance expense"=>"OP_Cos", "Tax expense"=>"tax", "Changes in inventories of finished goods and work in progress"=>"GP_Cos", "Raw materials and consumables used"=>"GP_Cos", "Employee benefit expenses"=>"OP_Cos", "Depreciation and amortisation expense"=>"OP_Cos", "Research and development"=>"OP_Cos", "Loss on property revaluation"=>"PAT_Cos", "Remeasurements of defined benefit pension schemes"=>"PAT_Cos", "Share of associates' other"=>"PAT_Cos", "Exchange gains arising on translation of foreign operations"=>"OP_Cos", "Inventories"=>"CA", "Trade and other receivables"=>"CA", "Available-for-sale investments"=>"NCA", "Derivative financial assets"=>"NCA", "Current tax assets"=>"CA", "Other assets"=>"NCA", "Cash and cash equivalents"=>"CA", "Assets in disposal groups classified as held for sale"=>"CA", "Finance lease receiveable"=>"NCA", "Property plant and equipment"=>"NCA", "Investment property"=>"NCA", "Goodwill"=>"NCA", "Other intangible assets"=>"NCA", "Other financial assets"=>"NCA", "Investments in equity-accounted associates"=>"NCA", "Investments in equity-accounted joint ventures"=>"NCA", "Other receivables"=>"CA", "Deferred tax assets"=>"CA", "Trade and other payables"=>"CL", "Loans and borrowings"=>"NCL", "Derivative financial liabilities"=>"NCL", "Income Tax Payable"=>"CL", "Employee benefit liabilities"=>"NCL", "Provisions"=>"CL", "Liabilities directly associated with assets in HFS"=>"CL", "Provisions "=>"NCL", "Deferred tax liability"=>"NCL", "Other financial liabilities"=>"NCL", "Deferred revenue"=>"NCL", "Other liabilities"=>"NCL", "Revaluation reserve"=>"EQ", "Available-for-sale reserve"=>"EQ", "Cash flow hedging reserve"=>"EQ", "Foreign exchange reserve"=>"EQ", "Issued capital and share premium"=>"EQ", "Other reserves"=>"EQ", "Retained earnings"=>"EQ", "Equity attributable to parent"=>"EQ", "Non-controlling interest"=>"EQ", "Share capital"=>"EQ", "Share premium reserve"=>"EQ", "Shares to be issued"=>"EQ", "No-Mapping"=>"EQ"})
      expect(tags.count).to eq 65
    end
  
  end
end
