AUTH_URI: https://accounts.google.com/o/oauth2/auth
CLIENT_SECRET: QOqjqlz_9jUm_2ov-uOkrDqo
CLIENT_ID: 464680693197-el77matr168lkhvasq6kebeep4gc9o1v.apps.googleusercontent.com

TOKEN_URI: https://accounts.google.com/o/oauth2/token
CLIENT_EMAIL: 792042861273-5b8b4e51kh4vrqompa2apjga6tge54jg@developer.gserviceaccount.com
REDIRECT_URIS: https://serene-brook-5729.herokuapp.com/signin/connect
CLIENT_X509_CERT_URL: https://www.googleapis.com/robot/v1/metadata/x509/901506026811-q0am03i585627ptu5r38o7cpkt8pk98l@developer.gserviceaccount.com

AUTH_PROVIDER_X509_CERT_URL: https://www.googleapis.com/oauth2/v1/certs
WINDOWS_CLIENT_ID: 0805eae6-bdf8-49c2-93cf-5a8aced01b36
WINDOWS_CLIENT_SECRET: pVCdXWDYnK9jB3brsoqmYUU
WINDOWS_REDIRECT_URI: https://serene-brook-5729.herokuapp.com/authorize
JAVASCRIPT_ORIGINS: https://serene-brook-5729.herokuapp.com/
PLUS_LOGIN_SCOPE: https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/plus.circles.read
